export const cinemaData = {
  IMAX: [
    {
      auditoriumId: 'AUD00001',
      theaterName: '남양주현대아울렛 스페이스원',
      auditoriumName: '1관',
      screenSize: '22m x 12m',
      soundType: 'Dolby Atmos',
      reviewCount: 3,
      averageReview: 3.8,
    },
    {
      auditoriumId: 'AUD00002',
      theaterName: '남양주현대아울렛 스페이스원',
      auditoriumName: '2관',
      screenSize: '22m x 12m',
      soundType: 'Dolby Atmos',
      reviewCount: 2,
      averageReview: 3.5,
    },
    {
      auditoriumId: 'AUD00003',
      theaterName: '대구 신세계(동대구)',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD00004',
      theaterName: '대전신세계아트앤사이언스',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD00005',
      theaterName: '송도(트리플스트리트)',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD00006',
      theaterName: '기타 등등',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD00007',
      theaterName: '추후 연결',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD00008',
      theaterName: '가나다',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD00009',
      theaterName: '라마바',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD00010',
      theaterName: '사아자',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
  ],
  'Dolby Cinema': [
    {
      auditoriumId: 'AUD-D0001',
      theaterName: '수원AK플라자(수원역)',
      auditoriumName: '1관',
      screenSize: 'IMAX Laser',
      soundType: 'Dolby Atmos',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD-D0002',
      theaterName: '수원AK플라자(수원역)',
      auditoriumName: '2관',
      screenSize: 'IMAX Laser',
      soundType: 'Dolby Atmos',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD-D0003',
      theaterName: '안성스타필드',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD-D0004',
      theaterName: '코엑스',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD-D0005',
      theaterName: '하남스타필드',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD-D0006',
      theaterName: '용산 CGV 아이맥스관',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
    {
      auditoriumId: 'AUD-D0007',
      theaterName: '추후연결',
      auditoriumName: '',
      screenSize: '',
      soundType: '',
      reviewCount: 0,
      averageReview: 0,
    },
  ],
};
