import type { BestReview } from '@/types/bestReview';
export const bestReviewMock: BestReview[] = [
  {
    reviewId: 101,
    reviewTitle: '몰입감이 좋은 상영관',
    thumbnailUrl: '',
    hashtags: ['몰입감좋음', '서라운드좋음', '좌석편안'],
    movieTitle: '어벤져스: 엔드게임',
    theaterName: 'CGV 용산아이파크몰',
    content: '사운드가 좋아서 더 몰입되는 거 같아요 꼭 여기서 보세요!!',
    userId: 1001,
    nickname: '아이언맨',
    profileImageUrl: '',
    heartCount: 542,
    originalCreatedAt: '2024-01-05T12:00:00Z',
    createdAt: '2024-01-05T12:10:00Z',
  },
  {
    reviewId: 102,
    reviewTitle: '영화 볼 때 음료수 많이 드시는 분',
    thumbnailUrl: '',
    hashtags: ['음향최고', '입출입편리'],
    movieTitle: '비상선언',
    theaterName: '롯데시네마 월드타워',
    content: '문이 가까워서 중간에 화장실 갈 때 눈치 안 봐도 됩니다! 대신 외부 소음이 조금 들림...',
    userId: 1002,
    nickname: '아몬드초콜릿',
    profileImageUrl: '',
    heartCount: 433,
    originalCreatedAt: '2024-01-06T14:00:00Z',
    createdAt: '2024-01-06T14:15:00Z',
  },
  {
    reviewId: 103,
    reviewTitle: '진짜 개구림',
    thumbnailUrl: '',
    hashtags: ['서라운드좋음', '입출입편리'],
    movieTitle: '좀비딸',
    theaterName: '메가박스 코엑스',
    content: '좌석이 진짜 개구려요 이런 자리를 이 돈 주고 파는 게 이해가 안됩니다;',
    userId: 1003,
    nickname: 'wow123',
    profileImageUrl: '',
    heartCount: 392,
    originalCreatedAt: '2024-01-07T16:30:00Z',
    createdAt: '2024-01-07T16:45:00Z',
  },
  {
    reviewId: 104,
    reviewTitle: '뮤지컬 영화에 걸맞는 사운드',
    thumbnailUrl: '',
    hashtags: ['소리선명', '시야탁트임', '연인이랑데이트'],
    movieTitle: '위키드2',
    theaterName: 'CGV 압구정',
    content: '뮤지컬 영화 보기에 딱 좋은 상영관입니다!! 좌석도 시야 좋았어요',
    userId: 1004,
    nickname: '떡볶이',
    profileImageUrl: '',
    heartCount: 481,
    originalCreatedAt: '2024-01-08T18:20:00Z',
    createdAt: '2024-01-08T18:30:00Z',
  },
  {
    reviewId: 105,
    reviewTitle: '자막 아니어도 보기 좋음',
    thumbnailUrl: '',
    hashtags: ['소리선명', '좌석편안', '혼자서'],
    movieTitle: '명탐정 코난: 척안의 잔상',
    theaterName: '롯데시네마 건대입구',
    content:
      '소리가 다른 상영관에 비해서 크고 선명한 것 같아요! 덕분에 대사가 잘 들려서 좋았습니당',
    userId: 1005,
    nickname: '채원',
    profileImageUrl: '',
    heartCount: 621,
    originalCreatedAt: '2024-01-09T10:00:00Z',
    createdAt: '2024-01-09T10:20:00Z',
  },
];
